### ISSUE TITLE
README.mdの貢献方法が存在しない

### ISSUE THREAD

**Issue by Chipsnet** [senshintou/web-site#32]
README.mdに`詳しくは貢献方法を御覧ください。`とありますが、クリックしても存在しないページに飛びます

**Comment by huequica** [comment]
@Chipsnet  
長期間の放置をお詫びします。すいませんでした。  
紆余曲折あり、現時点のPRをもってこのReposはArchiveすることにしました。  
`senshintou/web-site` を少しでも気にかけてくれたことに感謝申し上げます。ありがとうございました。
